#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
branch = $(git symbolic-ref --short -q HEAD)
git pull origin $branch
if [ "$?" == "0" ]; then
    git push origin $branch
    if [ "$?" == "0" ]; then
        echo "操作完成！"
    else 
        echo '推送代码失败！'
        exit 1
else 
    echo '拉取代码失败！'
    exit 1
